# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='reception_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
