# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-11 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0002_auto_20170809_1256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dbversion',
        ),
    ]
