# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-11 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0003_delete_dbversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dbversion',
            fields=[
                ('version', models.IntegerField(primary_key=True, serialize=False)),
                ('release', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dbversion',
            },
        ),
    ]
