# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0004_dbversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deposit',
            name='external_id',
            field=models.TextField(unique=True),
        ),
    ]
