# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-22 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0005_auto_20170818_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositRequestType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'deposit_request_type',
            },
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='type',
            field=models.ForeignKey(db_column='type', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='deposit.DepositRequestType'),
            preserve_default=False,
        ),
    ]
