# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-23 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0006_auto_20170922_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='external_id',
            field=models.TextField(),
        ),
    ]
