# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-11 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0014_auto_20180720_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrequest',
            name='type',
            field=models.CharField(choices=[
                ('archive', 'archive'),
                ('metadata', 'metadata')], max_length=8),
        ),
        migrations.DeleteModel(
            name='DepositRequestType',
        ),
    ]
